include: package:flutter_lints/flutter.yaml

analyzer:
  language:
    strict-inference: true
    strict-raw-types: true

linter:
  rules:
    - always_declare_return_types
    - prefer_final_locals
    - prefer_const_constructors
    - prefer_const_literals_to_create_immutables
    - avoid_print
    - use_build_context_synchronously
    - prefer_single_quotes
    - sort_child_properties_last
    - unawaited_futures
    - recursive_getters
    - avoid_empty_else
    - cancel_subscriptions
    - close_sinks
