// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart' show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError('DefaultFirebaseOptions are not supported for this platform.');
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDxBk8PwY8blRIlg0bP3aBHPCBgjqckCB0',
    appId: '1:1070097938760:web:5a98ccadeaf1349aaedb7d',
    messagingSenderId: '1070097938760',
    projectId: 'microwins-95da4',
    authDomain: 'microwins-95da4.firebaseapp.com',
    storageBucket: 'microwins-95da4.firebasestorage.app',
    measurementId: 'G-6D4NVPMTT4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDVI4Ja0PPppQAaI7yIA9pcveZGWCML__8',
    appId: '1:1070097938760:android:5a21c2e850a2cc9caedb7d',
    messagingSenderId: '1070097938760',
    projectId: 'microwins-95da4',
    storageBucket: 'microwins-95da4.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD4e12uNYSynB-TYHxdT7wTXMhcC3Yplmg',
    appId: '1:1070097938760:ios:3acbdf9939889956aedb7d',
    messagingSenderId: '1070097938760',
    projectId: 'microwins-95da4',
    storageBucket: 'microwins-95da4.firebasestorage.app',
    androidClientId: '1070097938760-fr3rm1kul2tooubld69kvqegrqc0mipo.apps.googleusercontent.com',
    iosClientId: '1070097938760-5j76ef0uj7fi9gan5l2lide3i8h80qab.apps.googleusercontent.com',
    iosBundleId: 'com.microwins.microwins',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD4e12uNYSynB-TYHxdT7wTXMhcC3Yplmg',
    appId: '1:1070097938760:ios:3acbdf9939889956aedb7d',
    messagingSenderId: '1070097938760',
    projectId: 'microwins-95da4',
    storageBucket: 'microwins-95da4.firebasestorage.app',
    androidClientId: '1070097938760-fr3rm1kul2tooubld69kvqegrqc0mipo.apps.googleusercontent.com',
    iosClientId: '1070097938760-5j76ef0uj7fi9gan5l2lide3i8h80qab.apps.googleusercontent.com',
    iosBundleId: 'com.microwins.microwins',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDxBk8PwY8blRIlg0bP3aBHPCBgjqckCB0',
    appId: '1:1070097938760:web:b836d87cbe65f028aedb7d',
    messagingSenderId: '1070097938760',
    projectId: 'microwins-95da4',
    authDomain: 'microwins-95da4.firebaseapp.com',
    storageBucket: 'microwins-95da4.firebasestorage.app',
    measurementId: 'G-CPQ9KP5H4Q',
  );
}
