// Mocks generated by Mockito 5.4.4 from annotations
// in microwins/test/features/habits/habit_view_model_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:microwins/features/habits/domain/entities/habit.dart' as _i4;
import 'package:microwins/features/habits/domain/habit_repository.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

/// A class which mocks [HabitRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockHabitRepository extends _i1.Mock implements _i2.HabitRepository {
  MockHabitRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<void> createHabit(_i4.Habit? habit) => (super.noSuchMethod(
        Invocation.method(
          #createHabit,
          [habit],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<void> updateHabit(_i4.Habit? habit) => (super.noSuchMethod(
        Invocation.method(
          #updateHabit,
          [habit],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<void> deleteHabit(String? id) => (super.noSuchMethod(
        Invocation.method(
          #deleteHabit,
          [id],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<List<_i4.Habit>> getHabits() => (super.noSuchMethod(
        Invocation.method(
          #getHabits,
          [],
        ),
        returnValue: _i3.Future<List<_i4.Habit>>.value(<_i4.Habit>[]),
      ) as _i3.Future<List<_i4.Habit>>);

  @override
  _i3.Stream<List<_i4.Habit>> watchHabits() => (super.noSuchMethod(
        Invocation.method(
          #watchHabits,
          [],
        ),
        returnValue: _i3.Stream<List<_i4.Habit>>.empty(),
      ) as _i3.Stream<List<_i4.Habit>>);

  @override
  _i3.Future<void> updateHabitsOrder(List<_i4.Habit>? habits) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateHabitsOrder,
          [habits],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<void> syncFromCloud() => (super.noSuchMethod(
        Invocation.method(
          #syncFromCloud,
          [],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);
}
